/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 appartment.gltf --transform
Author: vicente.plaza.cype (https://sketchfab.com/vicente.plaza.cype)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/appartments-building-bimservercenter-6dc0d4f9ef8442cfb8f27b4153179f3e
Title: Appartments building - BIMserver.center
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/appartment-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.Object_5637.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
      <lineSegments geometry={nodes.Object_6967.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_695.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Object_701.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_814.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_1719.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_1742.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_1743.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_1744.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_1745.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_1751.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_1752.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_1961.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_1962.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_2116.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Object_2117.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Object_2449.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_2450.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_2970.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_2992.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_2993.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_3041.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_3042.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_3081.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_3082.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_3091.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_3092.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_3097.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_3098.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_206.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_1372.geometry} material={materials.PaletteMaterial003} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4322.geometry} material={materials.PaletteMaterial004} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/appartment-transformed.glb')
